sa_sr_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: ShoulderJRotate
  pid:
    p: 160.5
    i: 91.0
    d: 8.0
    i_clamp: 90

sa_ss_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: ShoulderJSwing
  pid:
    p: 16000.0
    i: 6000.0
    d: 400.0
    i_clamp: 5000.0

sa_es_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: ElbowJSwing
  pid:
    p: 230.0
    i: 150.0
    d: 150.0
    i_clamp: 120.0

sa_er_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: ElbowJRotate
  pid:
    p: 24.0
    i: 18.0
    d: 15.0
    i_clamp: 1

r_arm_cartesian_pose_controller:
  type: robot_mechanism_controllers/CartesianPoseController
  root_name: shadowarm_base
  tip_name: palm
  fb_trans:
    p: 20.0
    i: 0.5
    d: 0.0
    i_clamp: 1.0
  fb_rot:
    p: 0.5
    i: 0.1
    d: 0.0
    i_clamp: 0.2

r_arm_joint_trajectory_controller:
  type: "sr_mechanism_controllers/JointTrajectoryActionController"
  joints:
    - ShoulderJRotate
    - ShoulderJSwing
    - ElbowJSwing
    - ElbowJRotate
    - WRJ2
    - WRJ1
  gains:
    ShoulderJRotate: {p: 600.5, i: 31.0, d: 8.0, i_clamp: 300.}
    ShoulderJSwing: {p: 300.0, i: 160.0, d: 400.0, i_clamp: 300.0}
    ElbowJSwing: {p: 930.0, i: 150.0, d: 150.0, i_clamp: 700.0}
    ElbowJRotate: {p: 240.0, i: 150.0, d: 15.0, i_clamp: 150.0}
    WRJ2: {p: 300.0, i: 0.0, d: 4.0, i_clamp: 2.0}
    WRJ1: {p: 300.0, i: 0.0, d: 4.0, i_clamp: 2.0}
  joint_trajectory_action_node:
    joints:
      - ShoulderJRotate
      - ShoulderJSwing
      - ElbowJSwing
      - ElbowJRotate
      - WRJ2
      - WRJ1
    constraints:
      goal_time: 30.0
      ShoulderJRotate:
        goal: 0.1
      ShoulderJSwing:
        goal: 0.1
      ElbowJSwing:
        goal: 0.1
      ElbowJRotate:
        goal: 0.1
      WRJ2:
        goal: 0.1
      WRJ1:
        goal: 0.1
